### ISSUE TITLE
Dependancy conflicts 

### ISSUE THREAD

**Issue by nmywrld** [cenksari/banking-app#1]
<img width="749" alt="Screenshot 2024-11-11 at 5 29 17 PM" src="https://github.com/user-attachments/assets/bd9e08d0-ae96-4c4f-a391-4d5048004973">

Referring to the image above, i ran npm install after zipping your master branch, and i faced this issue. any advice ?

**Comment by cenksari** [comment]
I'm using Yarn. Can you delete node_modules folder, yarn.lock file and run yarn install command.
